minecraft:
  name: 'minecraft'
  image:
    repository: 'itzg/minecraft-server'
    tag: 'latest'
    pullPolicy: 'IfNotPresent'
  server:
    port: 25565
    motd: 'A Minecraft Server'
    gamemode: 'survival'
    difficulty: 'normal'
  volume:
    size: '1Gi'
    path: '/data'
  resources:
    requests:
      memory: '1Gi'
      cpu: '500m'
    limits:
      memory: '2Gi'
      cpu: '1'

